set encoding=utf-8
set laststatus=2
set statusline=%<%f\ %m%r%h%w%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}%=%l,
set title
set number
set numberwidth=4
set expandtab
set tabstop=8
set shiftwidth=4
set noswapfile
set nobackup
set noundofile
